#!/usr/bin/env bash
# pinging the $1 5 times if $1 exists
# dispay a message if $1 does not exist
if [ $# -eq 1 ]; then
	ping -c 5 $1
elif [ $# -eq 0 ]; then
	echo 'Usage: 5-is_the_host_on_the_network {IP_ADDRESS}'
fi
