#!/usr/bin/env bash
# 4 bad luck, 8 good luck and Best School of rest
i=1
while [ $i -le 10 ]
do
	if [ $i -eq 4 ]; then
		echo 'bad luck'
	elif [ $i -eq 8 ]; then
		echo 'good luck'
	else
		echo 'Best School'
	fi
	i=$(( ++i ))
done
