#!/usr/bin/env bash
# running nginx as nginx
# get the user directive in nginx.conf
sed -i 's/^user .*/user nginx;/' /etc/nginx/nginx.conf

# Change the default port to 8080 in the default site configuration
sed -i 's/^listen 80 default_server;/listen 8080 default_server;/' /etc/nginx/sites-available/default

# Restart Nginx to apply the changes
service nginx restart

